### ISSUE TITLE
pccommon.sh issues & suggested fixes

### ISSUE THREAD

**Issue by jaime-gutierrez** [rsoprivatecloud/openstack-ops#1]
Issues: 

1. The ```rpc-instance-per-network-per-hypervisor``` function of ```pccommon.sh``` is broken as newer releases of RPC-O utilize underscores '_' in the container names rather than hyphens '-'. 

2. The STATE variable was using awk to search for``` '/status/'``` which there are more than one in the output of ```nova show $ID```

I've made the following test changes to the script which seemed to work ok on mitaka 13.1.3 utilizing the ```rpc-instance-per-network-per-hypervisor``` function. Can these changes be made to the script?

```
351c351
<     if [ ! "$( hostname | grep neutron-agents)" ]; then
---
>     if [ ! "$( hostname | grep neutron_agents)" ]; then
354c354
<       CONTAINER=`lxc-ls | grep neutron-agents |tail -1`
---
>       CONTAINER=`lxc-ls | grep neutron_agents |tail -1`
432c432
<     if [ ! "$( hostname | grep neutron-agents)" ]; then
---
>     if [ ! "$( hostname | grep neutron_agents)" ]; then
435c435
<       CONTAINER=`lxc-ls | grep neutron-agents`
---
>       CONTAINER=`lxc-ls | grep neutron_agents`
551c551
<     if [ ! "$( hostname | grep neutron-agents)" ]; then
---
>     if [ ! "$( hostname | grep neutron_agents)" ]; then
554c554
<       CONTAINER=`lxc-ls | grep neutron-agents`
---
>       CONTAINER=`lxc-ls | grep neutron_agents`
797c797
<   STATE=`nova show $ID | awk '/ status / { print $4 }'`
---
>   STATE=`nova show $ID | awk '/status/ { print $4 }'`
799c799
<     STATE=`nova show $ID | awk '/ status / { print $4 }'`
---
>     STATE=`nova show $ID | awk '/status/ { print $4 }'`
```

**Comment by toxick** [comment]
Yeah, Thomas brought the neutron[-_]agents thing to my attention.  Easy fix.  I'll take a look at the status thing and get back to you.

**Comment by BjoernT** [comment]
@jaime-gutierrez  Let me know if that is not fixing the problem.

**Comment by jaime-gutierrez** [comment]
Adding only a space to the right of status leaves the function broken still. A space needs to be in front of status as well as it is catching 'host_status' and 'status' from the output of nova show $ID.

**Comment by jaime-gutierrez** [comment]
I'm seeing that /opt/rpc-openstack/rpcd/playbooks/roles/rpc_support/tasks/pccommon_get.yml points to https://raw.githubusercontent.com/rsoprivatecloud/pubscripts/master/pccommon.sh , but that script doesn't have the updated fixes from commit  https://github.com/rsoprivatecloud/openstack-ops/commit/0ab6f72ba7ac3c24a567d7260cd7c6669841bdd8

**Comment by BjoernT** [comment]
Yeah let me update the reference

**Comment by BjoernT** [comment]
@jaime-gutierrez  Should be all ok now

**Comment by jaime-gutierrez** [comment]
It appears that the new link isn't working as expected, the script ends up only containing the new linked path rather than the contents of the script:

```
root@jaime-mitaka:/opt/rpc-openstack/openstack-ansible/playbooks# wget https://raw.githubusercontent.com/rsoprivatecloud/pubscripts/master/pccommon.sh
[...]
2017-01-30 19:01:33 (5.06 MB/s) - ‘pccommon.sh’ saved [31/31]

root@jaime-mitaka:/opt/rpc-openstack/openstack-ansible/playbooks# cat pccommon.sh
files/rpc-o-support/pccommon.sh
```

**Comment by BjoernT** [comment]
don't use the link use the reallocation at https://raw.githubusercontent.com/rsoprivatecloud/openstack-ops/mitaka-13.1/files/rpc-o-support/pccommon.sh The new version is not using the link anymore
