### ISSUE TITLE
New Cinder Commands Do Not Use the --all-tenants Flag

### ISSUE THREAD

**Issue by seancarlisle** [rsoprivatecloud/openstack-ops#3]
rpc-cinder-verify-lvm and rpc-cinder-verify-attach only check volumes for the scoped project, as opposed to all projects.

**Comment by seancarlisle** [comment]
I should also state that the associated awk for rpc-cinder-verify-attach will need to be modified. The reason for this is because when --all-tenant is specified, the 8th field is no longer the uuid of the instance the volume is attached to, but the "Bootable" flag.

**Comment by seancarlisle** [comment]
Fixed by e09e9ae.

**Comment by BjoernT** [comment]
e09e9ae is my commit, did a git accident happen here?

**Comment by BjoernT** [comment]
The right SHA would be 002b64583cd83cd8cd5dba7b681010436b38e613

**Comment by BjoernT** [comment]
OK fixed git repo. Always pull before push. Better fork this repo and create a pull request ;-)

**Comment by seancarlisle** [comment]
Did we push at the same time? I'll double check later.

**Comment by BjoernT** [comment]
no, not that I can see 
```
commit 002b64583cd83cd8cd5dba7b681010436b38e613
Author: seancarlisle <carlisle.sean@gmail.com>
Date:   Mon Feb 27 16:47:02 2017 -0600

    Fixed cinder commands not using --all-tenants

vs

commit 1ef64e208c5f4e627905d44ca61a0da95a96bd75
Merge: 89ec936 3977c70
Author: Bjoern Teipel <bjoern.teipel@rackspace.com>
Date:   Mon Feb 27 16:28:40 2017 -0600
```

it's fine now so don't worry
