### ISSUE TITLE
Role execution takes forever

### ISSUE THREAD

**Issue by odyssey4me** [rsoprivatecloud/openstack-ops#33]
The execution of this role takes more than 20 mins on an AIO, which is a single host. This is largely due to the fact that the playbook calling the role targets all hosts and containers and then the role does tasks based on inventory group. There is no use of dynamic inclusions or any form of host targeting to optimise the deployment time.

Considering what's being done in this role it's probably better implemented as a set of playbooks instead of as a role. Either that or dynamic inclusions should be used to only include the tasks for the targeted host group, and the information about that group should be given to it by the playbook.

It will be much simpler to re-implement the role as playbooks though, similar to how the rpc-maas role has been rewritten. This can also make it much easier to keep compatible with older versions of ansible.

Something else to note is that several tasks in this role are doing things which are already being done in OSA, or they are changing things being done in OSA (therefore the tasks are not idempotent). It'd be better to make use of the facilities provided to ensure that whatever OSA is doing is the right things from the start.

**Comment by BjoernT** [comment]
The module has been converted into a stand alone module, reducing run time by over 50%. 
Issue is closed with pull https://github.com/rsoprivatecloud/openstack-ops/pull/48
