### ISSUE TITLE
pccommon.sh - Add Cinder Snapshots to for rpc-cinder-verify-lvm and rpc-cinder-verify-attach 

### ISSUE THREAD

**Issue by brainerd123** [rsoprivatecloud/openstack-ops#6]
@toxick For rpc-cinder-verify-lvm and rpc-cinder-verify-attach in pccommon.sh can we please add cinder volume snapshots to the scope?

Thanks!
Andrew

**Comment by toxick** [comment]
Talked with Andrew.  Not high priority.  Will take a look at this when I get some time later today or early next week.

**Comment by toxick** [comment]
Snapshot checking is only valid in rpc-cinder-verify-lvm since you can't attach a snapshot directly.  Give it a whirl and let me know if you run into any problems.

**Comment by brainerd123** [comment]
Thanks @toxick . I will have @seancarlisle check it out and we'll get back to you.

**Comment by toxick** [comment]
Actually, I just found an issue with multiple snapshots on the same volume, I think.  Give me a bit to work on that.

**Comment by toxick** [comment]
Alrighty - should be good now.  <3
